### ISSUE TITLE
[Refactor] Reduce CSS code for variants via CSS variables

### ISSUE THREAD

**Issue by alaindet** [alaindet/pandivia#146]
Use "private" CSS variables to reduce CSS code associated to variants

From this

```css
.app-component.-primary {
  ._foo {
    ._bar {
      background-color: var(--app-color-primary);
    }
  }
}

.app-component.-secondary {
  ._foo {
    ._bar {
      background-color: var(--app-color-secondary);
    }
  }
}

.app-component.-tertiary {
  ._foo {
    ._bar {
      background-color: var(--app-color-tertiary);
    }
  }
}
```

To this

```css
.app-component {
  --_color-foobar: black;
  
  ._foo {
    ._bar {
      background-color: var(--_color-foobar);
    }
  }
}

.app-component.-primary {
  --_color-foobar: var(--app-color-primary);
}

.app-component.-secondary {
  --_color-foobar: var(--app-color-secondary);
}

.app-component.-tertiary {
  --_color-foobar: var(--app-color-tertiary);
}
```
